name: Upload to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Debug Secrets
      run: |
        echo "Bucket Name: ${{ secrets.R2_BUCKET_NAME }}"
        echo "Endpoint: ${{ secrets.R2_ENDPOINT }}"

    - name: Test R2 Connection
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        aws s3 ls s3://github --endpoint-url=https://ac34229f403bce2e69e97ed47465658c.r2.cloudflarestorage.com/github

    - name: Sync files to Cloudflare R2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        aws s3 sync . s3://github \
          --delete --exact-timestamps --debug \
          --exclude ".git/*" --exclude ".github/*" \
          --endpoint-url=${{ secrets.R2_ENDPOINT }} \
          --only-show-errors
