name: Upload to Cloudflare R2

on:
  push:
    branches:
      - main  # Активируется для push в ветку main

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 9d6216c32ede5bb3482ca34df6472dd5
        aws-secret-access-key: 662d3997a290ed6cdef84cf765e164cbdf55d73b755b88e26a3c0974357337bb
        aws-region: us-east-1  # Cloudflare R2 не использует region, но AWS CLI требует указания региона

    - name: Sync files to Cloudflare R2
      run: |
        aws s3 sync . s3://github --endpoint-url=https://ac34229f403bce2e69e97ed47465658c.r2.cloudflarestorage.com
